"""
Targeted Test: Force Serper 403 Forbidden and verify Groq AI Fallback
"""

import asyncio
import logging
from unittest.mock import patch
from app.database.connection import connect_to_mongo, close_mongo_connection, get_db
from app.services import task_service
from app.ai.orchestrator import WorkflowOrchestrator
from app.workflow.executor import WorkflowExecutor
from app.collection.search_providers import SearchProviderBlockedError

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("test_serper_403")


async def mock_search_403(*args, **kwargs):
    logger.info("[MockSearch] Simulating Serper 403 Forbidden")
    raise SearchProviderBlockedError("Serper API returned status 403 (Forbidden)")


async def run_403_fallback_test():
    await connect_to_mongo()
    db = get_db()

    prompt = "Find 5 Python developer jobs in Mumbai"
    logger.info("=== 1. Creating Task: '%s' ===", prompt)
    task = await task_service.create_task(prompt=prompt, record_limit=5)
    task_id = task["id"]

    logger.info("=== 2. Generating AI Plan ===")
    orchestrator = WorkflowOrchestrator()
    plan = await orchestrator.plan(task_id)

    logger.info("=== 3. Executing Workflow with Serper 403 Simulated ===")
    executor = WorkflowExecutor()
    with patch("app.collection.search_providers.SerperSearchProvider.search", side_effect=mock_search_403):
        exec_result = await executor.execute(task_id)

    logger.info("=== 4. Execution Finished ===")
    logger.info("Result Status: %s", exec_result.get("status"))
    logger.info("Result Progress: %s", exec_result.get("progress"))
    logger.info("Record Count: %s", exec_result.get("record_count"))
    logger.info("Fallback Used: %s", exec_result.get("fallback_used"))
    logger.info("Fallback Notice: %s", exec_result.get("fallback_notice"))

    assert exec_result.get("status") == "completed", f"Expected completed, got {exec_result.get('status')}"
    assert exec_result.get("progress") == 100, f"Expected progress 100, got {exec_result.get('progress')}"
    assert exec_result.get("fallback_used") is True, "Expected fallback_used to be True"
    assert exec_result.get("record_count", 0) > 0, "Expected at least 1 record generated by Groq fallback"

    # Verify MongoDB
    from bson import ObjectId
    db_task = await db.tasks.find_one({"_id": ObjectId(task_id)})
    assert db_task["status"] == "completed"
    assert db_task["progress"] == 100
    assert db_task.get("fallback_used") is True

    db_records = await db.dataset_records.find({"task_id": task_id}).to_list(length=10)
    logger.info("Stored fallback MongoDB records count: %d", len(db_records))
    for r in db_records:
        logger.info("Record data: %s", r.get("data"))

    await close_mongo_connection()
    logger.info("=== SERPER 403 FALLBACK TEST PASSED SUCCESSFULLY! ===")


if __name__ == "__main__":
    asyncio.run(run_403_fallback_test())
