"""
Extraction Models — Phase 4, Prompt 2

Pydantic models for structured records extracted from raw source content.

Key principle:
The `data` object inside `ExtractedRecord` MUST be DYNAMIC.
Field names and types inside `data` are governed by the dataset schema generated in Phase 3.
Do NOT hardcode fixed domain fields (such as job_title, salary, etc.).
"""

from datetime import datetime, timezone
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field, field_validator


class ExtractedRecord(BaseModel):
    """
    A single structured record extracted from a source page.

    The `data` dictionary contains dynamic field values corresponding
    to the dataset schema generated by Phase 3.
    """
    data: Dict[str, Any] = Field(
        ...,
        description="Dynamic key-value data dictionary matching the AI dataset schema"
    )
    source_url: str = Field(
        ...,
        description="Original source URL where this record was found"
    )
    source_title: Optional[str] = Field(
        default=None,
        description="Title of the source web page"
    )
    source_id: Optional[str] = Field(
        default=None,
        description="MongoDB ID of the source candidate document (if applicable)"
    )
    extracted_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when this record was extracted"
    )
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Extraction confidence score between 0.0 and 1.0 (represents field completeness and extraction quality)"
    )

    @field_validator("confidence")
    @classmethod
    def clamp_confidence(cls, v: float) -> float:
        return round(max(0.0, min(1.0, float(v))), 2)

    def to_dict(self) -> dict:
        """Convert model to a JSON-serializable dictionary."""
        return {
            "data": self.data,
            "source_url": self.source_url,
            "source_title": self.source_title,
            "source_id": self.source_id,
            "extracted_at": self.extracted_at.isoformat() if isinstance(self.extracted_at, datetime) else str(self.extracted_at),
            "confidence": self.confidence,
        }


class ExtractionResult(BaseModel):
    """
    Wrapper payload for all records extracted from a single source document.
    """
    source_id: Optional[str] = Field(
        default=None,
        description="ID of the source candidate document"
    )
    source_url: str = Field(
        ...,
        description="URL of the source"
    )
    source_title: Optional[str] = Field(
        default=None,
        description="Title of the source page"
    )
    records: List[ExtractedRecord] = Field(
        default_factory=list,
        description="List of extracted structured records"
    )
    total_records: int = Field(
        default=0,
        description="Total number of valid records extracted"
    )
    status: str = Field(
        default="extracted",
        description="Status: 'extracted', 'failed', 'empty'"
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Error details if extraction failed"
    )
    extracted_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when extraction completed"
    )

    def to_dict(self) -> dict:
        """Convert result wrapper to a JSON-serializable dictionary."""
        return {
            "source_id": self.source_id,
            "source_url": self.source_url,
            "source_title": self.source_title,
            "records": [r.to_dict() for r in self.records],
            "total_records": len(self.records),
            "status": self.status,
            "error_message": self.error_message,
            "extracted_at": self.extracted_at.isoformat() if isinstance(self.extracted_at, datetime) else str(self.extracted_at),
        }
