"""
Processing Models — Phase 4, Prompt 3

Pydantic models and data structures for the Data Cleaning, Normalization,
Validation, and Deduplication pipeline.

Domain-agnostic: Supports dynamic dataset schemas generated by Phase 3.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field, field_validator


class ValidationStatus(str, Enum):
    """Status classification for processed records."""
    VALID = "valid"
    INVALID = "invalid"
    WARNING = "warning"


class ValidationErrorItem(BaseModel):
    """Details of a single validation error or schema violation."""
    record_index: int = Field(..., description="Index of the record in the batch")
    field: Optional[str] = Field(None, description="Name of the field associated with the error")
    message: str = Field(..., description="Human-readable error explanation")

    def to_dict(self) -> dict:
        return {
            "record_index": self.record_index,
            "field": self.field,
            "message": self.message,
        }


class ValidationResult(BaseModel):
    """Output container returned by DataValidator."""
    valid: bool = Field(default=True, description="Whether the record passed schema validation")
    errors: List[ValidationErrorItem] = Field(default_factory=list, description="List of validation errors")
    warnings: List[str] = Field(default_factory=list, description="Non-fatal warnings")

    def to_dict(self) -> dict:
        return {
            "valid": self.valid,
            "errors": [e.to_dict() for e in self.errors],
            "warnings": self.warnings,
        }


class DeduplicationResult(BaseModel):
    """Output container returned by DataDeduplicator."""
    records: List[Dict[str, Any]] = Field(default_factory=list, description="Unique clean records")
    duplicates_removed: int = Field(default=0, description="Count of duplicate records removed")
    duplicate_candidates: int = Field(default=0, description="Count of potential fuzzy duplicate candidates flagged")

    def to_dict(self) -> dict:
        return {
            "records": self.records,
            "duplicates_removed": self.duplicates_removed,
            "duplicate_candidates": self.duplicate_candidates,
        }


class ProcessingResult(BaseModel):
    """
    Final output container produced by DataProcessingPipeline.
    Encapsulates input, stage counters, errors, and final unique clean records.
    """
    task_id: Optional[str] = Field(None, description="MongoDB task ID")
    input_count: int = Field(default=0, description="Number of raw extracted input records")
    cleaned_count: int = Field(default=0, description="Number of records after cleaning phase")
    valid_count: int = Field(default=0, description="Number of records passing validation")
    invalid_count: int = Field(default=0, description="Number of records rejected during validation")
    duplicates_removed: int = Field(default=0, description="Number of duplicate records removed")
    final_count: int = Field(default=0, description="Final count of clean unique valid records")
    records: List[Dict[str, Any]] = Field(default_factory=list, description="Final processed records")
    errors: List[Dict[str, Any]] = Field(default_factory=list, description="Collected record-level error details")
    warnings: List[str] = Field(default_factory=list, description="Collected warning messages")
    processed_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when processing completed"
    )

    def to_dict(self) -> dict:
        return {
            "task_id": self.task_id,
            "input_count": self.input_count,
            "cleaned_count": self.cleaned_count,
            "valid_count": self.valid_count,
            "invalid_count": self.invalid_count,
            "duplicates_removed": self.duplicates_removed,
            "final_count": self.final_count,
            "records": self.records,
            "errors": self.errors,
            "warnings": self.warnings,
            "processed_at": self.processed_at.isoformat() if isinstance(self.processed_at, datetime) else str(self.processed_at),
        }
